on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run
        type: choice
        required: true
        options:
          - dev
          - staging
          - prod
        

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, world!"
